version: 3

tasks:
  docs-serve:
    cmds:
      - docker run --name yurl-mk-docs --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material:latest

  build-image:
    vars:
      IMAGE_NAME: "{{.IMAGE_NAME}}"
      IMAGE_TAG: "{{.IMAGE_TAG}}"
    cmds:
      - docker build -t {{ .IMAGE_NAME | default "yurl" }}:{{ .IMAGE_TAG | default "latest" }} .

  generate-vhs-tapes:
    silent: true
    vars:
      TAPE_FILES:
        sh: ls ./docs/vhs-tapes/*.tape | xargs
    cmds:
      - |
        {{ range $i, $line := .TAPE_FILES | splitList " " }}
          echo Generating: {{ $line }}
          vhs {{ $line }}
        {{- end -}}
